apiVersion: apps/v1
kind: Deployment
metadata:
  name: diplom-app
  namespace: default
  labels:
    app: diplom-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diplom-app
  template:
    metadata:
      labels:
        app: diplom-app
    spec:
      containers:
      - name: app
        image: cr.yandex/crpajqvnc6vh3duplq4s/diplom-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: diplom-app-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: diplom-app
  ports:
  - port: 80
    targetPort: 80