name: Build and Deploy

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

env:
  REGISTRY_ID: ${{ secrets.YC_REGISTRY_ID }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Получаем IAM-токен для сервисного аккаунта
    - name: Get IAM token
      id: get-iam-token
      uses: yc-actions/yc-iam-token@v1
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CONTENT }}
    
    # Логинимся в Container Registry с помощью IAM-токена
    - name: Login to Yandex Cloud Container Registry
      run: |
        echo ${{ steps.get-iam-token.outputs.token }} | docker login \
          --username iam \
          --password-stdin \
          cr.yandex
    
    # Собираем и пушим образ
    - name: Build and push Docker image
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          TAG=${GITHUB_REF#refs/tags/}
        else
          TAG=${GITHUB_SHA::8}
        fi
        
        docker build -t cr.yandex/$REGISTRY_ID/diplom-app:$TAG .
        docker tag cr.yandex/$REGISTRY_ID/diplom-app:$TAG cr.yandex/$REGISTRY_ID/diplom-app:latest
        docker push cr.yandex/$REGISTRY_ID/diplom-app --all-tags
    
    # Деплой при создании тега
    - name: Setup kubectl
      if: startsWith(github.ref, 'refs/tags/')
      uses: azure/setup-kubectl@v4
    
    - name: Configure kubectl
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=$(pwd)/kubeconfig.yaml
        kubectl cluster-info
    
    - name: Deploy to Kubernetes
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        export KUBECONFIG=$(pwd)/kubeconfig.yaml
        TAG=${GITHUB_REF#refs/tags/}
        kubectl set image deployment/diplom-app app=cr.yandex/$REGISTRY_ID/diplom-app:$TAG --record
        kubectl rollout status deployment/diplom-app
